[2023-09-21T02:11:55.724+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.f manual__2023-09-21T02:11:48.772778+00:00 [queued]>
[2023-09-21T02:11:55.730+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.f manual__2023-09-21T02:11:48.772778+00:00 [queued]>
[2023-09-21T02:11:55.730+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-21T02:11:55.741+0000] {taskinstance.py:1380} INFO - Executing <Task(CopyFromExternalStageToSnowflakeOperator): f> on 2023-09-21 02:11:48.772778+00:00
[2023-09-21T02:11:55.746+0000] {standard_task_runner.py:57} INFO - Started process 3086 to run task
[2023-09-21T02:11:55.749+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'f', 'manual__2023-09-21T02:11:48.772778+00:00', '--job-id', '527', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmp8f63h9n1']
[2023-09-21T02:11:55.751+0000] {standard_task_runner.py:85} INFO - Job 527: Subtask f
[2023-09-21T02:11:55.787+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.f manual__2023-09-21T02:11:48.772778+00:00 [running]> on host fd67d4db30a8
[2023-09-21T02:11:55.848+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='f' AIRFLOW_CTX_EXECUTION_DATE='2023-09-21T02:11:48.772778+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-21T02:11:48.772778+00:00'
[2023-09-21T02:11:55.849+0000] {copy_into_snowflake.py:139} INFO - Executing COPY command...
[2023-09-21T02:11:55.857+0000] {base.py:73} INFO - Using connection ID 'snowflake_conn_id' for task execution.
[2023-09-21T02:11:55.857+0000] {connection.py:314} INFO - Snowflake Connector for Python Version: 3.1.1, Python Version: 3.8.18, Platform: Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.2.5
[2023-09-21T02:11:55.857+0000] {connection.py:1050} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-09-21T02:11:55.858+0000] {connection.py:1068} INFO - Setting use_openssl_only mode to False
[2023-09-21T02:11:55.858+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/transfers/copy_into_snowflake.py", line 140, in execute
    snowflake_hook.run(sql=sql, autocommit=self.autocommit)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 409, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 303, in get_conn
    conn = connector.connect(**conn_config)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/__init__.py", line 51, in Connect
    return SnowflakeConnection(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 353, in __init__
    self.connect(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 625, in connect
    self.__open_connection()
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 832, in __open_connection
    self._session_parameters[
TypeError: 'str' object does not support item assignment
[2023-09-21T02:11:55.864+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=f, execution_date=20230921T021148, start_date=20230921T021155, end_date=20230921T021155
[2023-09-21T02:11:55.874+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 527 for task f ('str' object does not support item assignment; 3086)
[2023-09-21T02:11:55.882+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-21T02:11:55.894+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
