[2023-09-20T20:01:10.438+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T20:01:09.362157+00:00 [queued]>
[2023-09-20T20:01:10.446+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T20:01:09.362157+00:00 [queued]>
[2023-09-20T20:01:10.446+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:01:10.458+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 20:01:09.362157+00:00
[2023-09-20T20:01:10.463+0000] {standard_task_runner.py:57} INFO - Started process 1160 to run task
[2023-09-20T20:01:10.470+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T20:01:09.362157+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpvsuftyue']
[2023-09-20T20:01:10.472+0000] {standard_task_runner.py:85} INFO - Job 110: Subtask create_dataframe_student
[2023-09-20T20:01:10.514+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T20:01:09.362157+00:00 [running]> on host 6086152831d6
[2023-09-20T20:01:10.766+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T20:01:09.362157+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T20:01:09.362157+00:00'
[2023-09-20T20:01:10.767+0000] {logging_mixin.py:151} INFO - read_student_data
[2023-09-20T20:01:10.785+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 37, in create_dataframe
    json_data = xcom_pull_obj[0]
TypeError: 'NoneType' object is not subscriptable
[2023-09-20T20:01:10.804+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T200109, start_date=20230920T200110, end_date=20230920T200110
[2023-09-20T20:01:10.817+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 110 for task create_dataframe_student ('NoneType' object is not subscriptable; 1160)
[2023-09-20T20:01:10.840+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:01:10.858+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
