[2023-09-20T20:00:00.528+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:59:59.740960+00:00 [queued]>
[2023-09-20T20:00:00.538+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:59:59.740960+00:00 [queued]>
[2023-09-20T20:00:00.538+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-09-20T20:00:00.550+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_dataframe_student> on 2023-09-20 19:59:59.740960+00:00
[2023-09-20T20:00:00.555+0000] {standard_task_runner.py:57} INFO - Started process 1132 to run task
[2023-09-20T20:00:00.558+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'student_semantic', 'create_dataframe_student', 'manual__2023-09-20T19:59:59.740960+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/student_semantic.py', '--cfg-path', '/tmp/tmpa2vvjcxo']
[2023-09-20T20:00:00.561+0000] {standard_task_runner.py:85} INFO - Job 107: Subtask create_dataframe_student
[2023-09-20T20:00:00.603+0000] {task_command.py:415} INFO - Running <TaskInstance: student_semantic.create_dataframe_student manual__2023-09-20T19:59:59.740960+00:00 [running]> on host 6086152831d6
[2023-09-20T20:00:00.673+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='student_semantic' AIRFLOW_CTX_TASK_ID='create_dataframe_student' AIRFLOW_CTX_EXECUTION_DATE='2023-09-20T19:59:59.740960+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-20T19:59:59.740960+00:00'
[2023-09-20T20:00:00.868+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/packages/student_semantic/student_semantic.py", line 37, in create_dataframe
    json_data = xcom_pull_obj[0]
TypeError: 'NoneType' object is not subscriptable
[2023-09-20T20:00:00.875+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=student_semantic, task_id=create_dataframe_student, execution_date=20230920T195959, start_date=20230920T200000, end_date=20230920T200000
[2023-09-20T20:00:00.886+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 107 for task create_dataframe_student ('NoneType' object is not subscriptable; 1132)
[2023-09-20T20:00:00.932+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-20T20:00:00.949+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
